dbMemo "SQL" ="UPDATE tblArticoli SET tblArticoli.SConsumo = [iSConsumo], tblArticoli.SSpedito "
    "= [iSSpedito], tblArticoli.Num_Eventi = [iNum_Eventi], tblArticoli.Anno_Calcolo "
    "= [iAnno_Calcolo], tblArticoli.Mese_Calcolo = [iMese_Calcolo], tblArticoli.Mesi_"
    "Consumo = [iMesi_Consumo]\015\012WHERE (((tblArticoli.Cod_Art)=[iCod_Art]));\015"
    "\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbBoolean "OrderByOn" ="0"
dbByte "Orientation" ="0"
dbByte "DefaultView" ="2"
dbBoolean "FilterOnLoad" ="0"
dbBoolean "OrderByOnLoad" ="-1"
Begin
End
