dbMemo "SQL" ="INSERT INTO tblCOrdersStorico ( soc_ord, soc_sped, tipo_doc, numero_doc, riga_do"
    "c, cod_cli, ds_rag_soc, utente, stato, liv_urgenza, data_ordine, data_prev_cons,"
    " cod_art, descrizione, Giorni_Lt, flag_stock_out, qta_ord_umv, qta_cons_umv, tip"
    "o_riord, lead_time, ROP, ROQ, CS_CSC, IMPORTO_NETTO, clm, respro, UpdateDate )\015"
    "\012VALUES (isoc_ord, isoc_sped, itipo_doc, inumero_doc, iriga_doc, icod_cli, id"
    "s_rag_soc, iutente, istato, iliv_urgenza, idata_ordine, idata_prev_cons, icod_ar"
    "t, idescrizione, iGiorni_Lt, iflag_stock_out, iqta_ord_umv, iqta_cons_umv, itipo"
    "_riord, ilead_time, iROP, iROQ, iCS_CSC, iIMPORTO_NETTO, iclm, irespro, iUpdateD"
    "ate);\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbBoolean "OrderByOn" ="0"
dbByte "Orientation" ="0"
dbByte "DefaultView" ="2"
dbBoolean "FilterOnLoad" ="0"
dbBoolean "OrderByOnLoad" ="-1"
Begin
End
