dbMemo "SQL" ="SELECT DISTINCTROW tblTopics.strSampleCategory\015\012FROM tblTopics\015\012GROU"
    "P BY tblTopics.strSampleCategory\015\012ORDER BY tblTopics.strSampleCategory;\015"
    "\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbByte "RecordsetType" ="0"
dbBoolean "OrderByOn" ="0"
dbByte "Orientation" ="0"
dbByte "DefaultView" ="2"
dbBoolean "FilterOnLoad" ="0"
dbBoolean "OrderByOnLoad" ="-1"
dbBoolean "TotalsRow" ="0"
Begin
End
