Version =20
VersionRequired =20
Begin Form
    RecordSelectors = NotDefault
    AutoCenter = NotDefault
    NavigationButtons = NotDefault
    AllowAdditions = NotDefault
    AllowDesignChanges = NotDefault
    ScrollBars =0
    TabularFamily =48
    PictureAlignment =2
    DatasheetGridlinesBehavior =3
    GridY =10
    Width =10601
    DatasheetFontHeight =10
    ItemSuffix =181
    Left =9045
    Top =1455
    Right =19920
    Bottom =6420
    DatasheetGridlinesColor =12632256
    RecSrcDt = Begin
        0x3be9564defffe340
    End
    Caption ="frmCategoriaEventiCvaValCalc"
    DatasheetFontName ="Arial"
    PrtMip = Begin
        0x6801000068010000680100006801000000000000201c0000e010000001000000 ,
        0x010000006801000000000000a10700000100000001000000
    End
    FilterOnLoad =0
    DatasheetBackColor12 =16777215
    ShowPageMargins =0
    DisplayOnSharePointSite =0
    DatasheetGridlinesColor12 =12632256
    Begin
        Begin Label
            BackStyle =0
            BackColor =-2147483633
            ForeColor =-2147483630
            LeftPadding =30
            TopPadding =30
            RightPadding =30
            BottomPadding =30
            GridlineStyleLeft =0
            GridlineStyleTop =0
            GridlineStyleRight =0
            GridlineStyleBottom =0
            GridlineWidthLeft =1
            GridlineWidthTop =1
            GridlineWidthRight =1
            GridlineWidthBottom =1
        End
        Begin Rectangle
            SpecialEffect =3
            BackStyle =0
            Width =850
            Height =850
            LeftPadding =30
            TopPadding =30
            RightPadding =30
            BottomPadding =30
            GridlineStyleLeft =0
            GridlineStyleTop =0
            GridlineStyleRight =0
            GridlineStyleBottom =0
            GridlineWidthLeft =1
            GridlineWidthTop =1
            GridlineWidthRight =1
            GridlineWidthBottom =1
        End
        Begin Line
            Width =1701
            LeftPadding =30
            TopPadding =30
            RightPadding =30
            BottomPadding =30
            GridlineStyleLeft =0
            GridlineStyleTop =0
            GridlineStyleRight =0
            GridlineStyleBottom =0
            GridlineWidthLeft =1
            GridlineWidthTop =1
            GridlineWidthRight =1
            GridlineWidthBottom =1
        End
        Begin Image
            BackStyle =0
            OldBorderStyle =0
            PictureAlignment =2
            Width =1701
            Height =1701
            LeftPadding =30
            TopPadding =30
            RightPadding =30
            BottomPadding =30
            GridlineStyleLeft =0
            GridlineStyleTop =0
            GridlineStyleRight =0
            GridlineStyleBottom =0
            GridlineWidthLeft =1
            GridlineWidthTop =1
            GridlineWidthRight =1
            GridlineWidthBottom =1
        End
        Begin CommandButton
            Width =1701
            Height =283
            FontSize =8
            FontWeight =400
            FontName ="MS Sans Serif"
            LeftPadding =30
            TopPadding =30
            RightPadding =30
            BottomPadding =30
            GridlineStyleLeft =0
            GridlineStyleTop =0
            GridlineStyleRight =0
            GridlineStyleBottom =0
            GridlineWidthLeft =1
            GridlineWidthTop =1
            GridlineWidthRight =1
            GridlineWidthBottom =1
        End
        Begin OptionButton
            SpecialEffect =2
            LabelX =230
            LabelY =-30
            LeftPadding =30
            TopPadding =30
            RightPadding =30
            BottomPadding =30
            GridlineStyleLeft =0
            GridlineStyleTop =0
            GridlineStyleRight =0
            GridlineStyleBottom =0
            GridlineWidthLeft =1
            GridlineWidthTop =1
            GridlineWidthRight =1
            GridlineWidthBottom =1
        End
        Begin CheckBox
            SpecialEffect =2
            LabelX =230
            LabelY =-30
            LeftPadding =30
            TopPadding =30
            RightPadding =30
            BottomPadding =30
            GridlineStyleLeft =0
            GridlineStyleTop =0
            GridlineStyleRight =0
            GridlineStyleBottom =0
            GridlineWidthLeft =1
            GridlineWidthTop =1
            GridlineWidthRight =1
            GridlineWidthBottom =1
        End
        Begin OptionGroup
            SpecialEffect =3
            Width =1701
            Height =1701
            LeftPadding =30
            TopPadding =30
            RightPadding =30
            BottomPadding =30
            GridlineStyleLeft =0
            GridlineStyleTop =0
            GridlineStyleRight =0
            GridlineStyleBottom =0
            GridlineWidthLeft =1
            GridlineWidthTop =1
            GridlineWidthRight =1
            GridlineWidthBottom =1
        End
        Begin BoundObjectFrame
            SpecialEffect =2
            OldBorderStyle =0
            BackStyle =0
            Width =4536
            Height =2835
            LabelX =-1701
            LeftPadding =30
            TopPadding =30
            RightPadding =30
            BottomPadding =30
            GridlineStyleLeft =0
            GridlineStyleTop =0
            GridlineStyleRight =0
            GridlineStyleBottom =0
            GridlineWidthLeft =1
            GridlineWidthTop =1
            GridlineWidthRight =1
            GridlineWidthBottom =1
        End
        Begin TextBox
            FELineBreak = NotDefault
            SpecialEffect =2
            Width =1701
            LabelX =-1701
            BackColor =-2147483643
            ForeColor =-2147483640
            AsianLineBreak =255
            LeftPadding =30
            TopPadding =30
            RightPadding =30
            BottomPadding =30
            GridlineStyleLeft =0
            GridlineStyleTop =0
            GridlineStyleRight =0
            GridlineStyleBottom =0
            GridlineWidthLeft =1
            GridlineWidthTop =1
            GridlineWidthRight =1
            GridlineWidthBottom =1
            ShowDatePicker =1
        End
        Begin ListBox
            SpecialEffect =2
            Width =1701
            Height =1417
            LabelX =-1701
            BackColor =-2147483643
            ForeColor =-2147483640
            LeftPadding =30
            TopPadding =30
            RightPadding =30
            BottomPadding =30
            GridlineStyleLeft =0
            GridlineStyleTop =0
            GridlineStyleRight =0
            GridlineStyleBottom =0
            GridlineWidthLeft =1
            GridlineWidthTop =1
            GridlineWidthRight =1
            GridlineWidthBottom =1
        End
        Begin ComboBox
            SpecialEffect =2
            Width =1701
            LabelX =-1701
            BackColor =-2147483643
            ForeColor =-2147483640
            LeftPadding =30
            TopPadding =30
            RightPadding =30
            BottomPadding =30
            GridlineStyleLeft =0
            GridlineStyleTop =0
            GridlineStyleRight =0
            GridlineStyleBottom =0
            GridlineWidthLeft =1
            GridlineWidthTop =1
            GridlineWidthRight =1
            GridlineWidthBottom =1
        End
        Begin Subform
            SpecialEffect =2
            Width =1701
            Height =1701
            LeftPadding =30
            TopPadding =30
            RightPadding =30
            BottomPadding =30
            GridlineStyleLeft =0
            GridlineStyleTop =0
            GridlineStyleRight =0
            GridlineStyleBottom =0
            GridlineWidthLeft =1
            GridlineWidthTop =1
            GridlineWidthRight =1
            GridlineWidthBottom =1
        End
        Begin UnboundObjectFrame
            SpecialEffect =2
            OldBorderStyle =1
            Width =4536
            Height =2835
            LeftPadding =30
            TopPadding =30
            RightPadding =30
            BottomPadding =30
            GridlineStyleLeft =0
            GridlineStyleTop =0
            GridlineStyleRight =0
            GridlineStyleBottom =0
            GridlineWidthLeft =1
            GridlineWidthTop =1
            GridlineWidthRight =1
            GridlineWidthBottom =1
        End
        Begin ToggleButton
            Width =283
            Height =283
            FontSize =8
            FontWeight =400
            FontName ="MS Sans Serif"
            LeftPadding =30
            TopPadding =30
            RightPadding =30
            BottomPadding =30
            GridlineStyleLeft =0
            GridlineStyleTop =0
            GridlineStyleRight =0
            GridlineStyleBottom =0
            GridlineWidthLeft =1
            GridlineWidthTop =1
            GridlineWidthRight =1
            GridlineWidthBottom =1
        End
        Begin Tab
            BackStyle =0
            Width =5103
            Height =3402
            LeftPadding =30
            TopPadding =30
            RightPadding =30
            BottomPadding =30
            GridlineStyleLeft =0
            GridlineStyleTop =0
            GridlineStyleRight =0
            GridlineStyleBottom =0
            GridlineWidthLeft =1
            GridlineWidthTop =1
            GridlineWidthRight =1
            GridlineWidthBottom =1
        End
        Begin FormHeader
            Height =585
            BackColor =52479
            Name ="IntestazioneMaschera"
            Begin
                Begin Label
                    OverlapFlags =93
                    TextFontCharSet =161
                    TextAlign =1
                    Top =300
                    Width =340
                    Height =285
                    FontSize =11
                    Name ="ID_Employee_Etichetta"
                    Caption ="Cl"
                    FontName ="Calibri"
                    Tag ="DetachedLabel"
                    LayoutCachedTop =300
                    LayoutCachedWidth =340
                    LayoutCachedHeight =585
                End
                Begin Label
                    OverlapFlags =223
                    TextFontCharSet =161
                    TextAlign =2
                    Left =330
                    Top =300
                    Width =1021
                    Height =285
                    FontSize =11
                    FontWeight =700
                    ForeColor =2366701
                    Name ="FirstName_Etichetta"
                    Caption ="A1"
                    FontName ="Calibri"
                    Tag ="DetachedLabel"
                    LayoutCachedLeft =330
                    LayoutCachedTop =300
                    LayoutCachedWidth =1351
                    LayoutCachedHeight =585
                End
                Begin Label
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =1352
                    Top =300
                    Width =1021
                    Height =285
                    FontSize =11
                    FontWeight =700
                    ForeColor =2366701
                    Name ="Etichetta53"
                    Caption ="A2"
                    FontName ="Calibri"
                    Tag ="DetachedLabel"
                    LayoutCachedLeft =1352
                    LayoutCachedTop =300
                    LayoutCachedWidth =2373
                    LayoutCachedHeight =585
                End
                Begin Label
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =2374
                    Top =300
                    Width =1021
                    Height =285
                    FontSize =11
                    FontWeight =700
                    ForeColor =2366701
                    Name ="Etichetta60"
                    Caption ="A3"
                    FontName ="Calibri"
                    Tag ="DetachedLabel"
                    LayoutCachedLeft =2374
                    LayoutCachedTop =300
                    LayoutCachedWidth =3395
                    LayoutCachedHeight =585
                End
                Begin Label
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =3396
                    Top =300
                    Width =1021
                    Height =285
                    FontSize =11
                    FontWeight =700
                    ForeColor =2366701
                    Name ="Etichetta61"
                    Caption ="A4"
                    FontName ="Calibri"
                    Tag ="DetachedLabel"
                    LayoutCachedLeft =3396
                    LayoutCachedTop =300
                    LayoutCachedWidth =4417
                    LayoutCachedHeight =585
                End
                Begin Label
                    OverlapFlags =93
                    TextFontCharSet =161
                    TextAlign =2
                    Left =4418
                    Top =300
                    Width =1021
                    Height =285
                    FontSize =11
                    FontWeight =700
                    ForeColor =-2147483615
                    Name ="Etichetta62"
                    Caption ="B1"
                    FontName ="Calibri"
                    Tag ="DetachedLabel"
                    LayoutCachedLeft =4418
                    LayoutCachedTop =300
                    LayoutCachedWidth =5439
                    LayoutCachedHeight =585
                End
                Begin Label
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =5440
                    Top =300
                    Width =1021
                    Height =285
                    FontSize =11
                    FontWeight =700
                    ForeColor =-2147483615
                    Name ="Etichetta63"
                    Caption ="B2"
                    FontName ="Calibri"
                    Tag ="DetachedLabel"
                    LayoutCachedLeft =5440
                    LayoutCachedTop =300
                    LayoutCachedWidth =6461
                    LayoutCachedHeight =585
                End
                Begin Label
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =6462
                    Top =300
                    Width =1021
                    Height =285
                    FontSize =11
                    FontWeight =700
                    ForeColor =-2147483615
                    Name ="Etichetta64"
                    Caption ="B3"
                    FontName ="Calibri"
                    Tag ="DetachedLabel"
                    LayoutCachedLeft =6462
                    LayoutCachedTop =300
                    LayoutCachedWidth =7483
                    LayoutCachedHeight =585
                End
                Begin Label
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =7484
                    Top =300
                    Width =1021
                    Height =285
                    FontSize =11
                    FontWeight =700
                    Name ="Etichetta65"
                    Caption ="C1"
                    FontName ="Calibri"
                    Tag ="DetachedLabel"
                    LayoutCachedLeft =7484
                    LayoutCachedTop =300
                    LayoutCachedWidth =8505
                    LayoutCachedHeight =585
                End
                Begin Label
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =8506
                    Top =300
                    Width =1021
                    Height =285
                    FontSize =11
                    FontWeight =700
                    Name ="Etichetta66"
                    Caption ="C2"
                    FontName ="Calibri"
                    Tag ="DetachedLabel"
                    LayoutCachedLeft =8506
                    LayoutCachedTop =300
                    LayoutCachedWidth =9527
                    LayoutCachedHeight =585
                End
                Begin Label
                    OverlapFlags =87
                    TextFontCharSet =161
                    TextAlign =2
                    Left =9528
                    Top =300
                    Width =1021
                    Height =285
                    FontSize =11
                    FontWeight =700
                    Name ="Etichetta167"
                    Caption ="TOT"
                    FontName ="Calibri"
                    Tag ="DetachedLabel"
                    LayoutCachedLeft =9528
                    LayoutCachedTop =300
                    LayoutCachedWidth =10549
                    LayoutCachedHeight =585
                End
                Begin Label
                    OverlapFlags =215
                    TextFontFamily =0
                    Left =1351
                    Width =3811
                    Height =375
                    FontSize =15
                    BackColor =16777215
                    BorderColor =16251385
                    ForeColor =255
                    Name ="Auto_Title0"
                    Caption ="Costo Giacenza Calcolato"
                    FontName ="Trebuchet"
                    LayoutCachedLeft =1351
                    LayoutCachedWidth =5162
                    LayoutCachedHeight =375
                End
                Begin Label
                    OverlapFlags =85
                    TextFontFamily =0
                    Width =735
                    Height =225
                    FontWeight =700
                    BackColor =16777215
                    BorderColor =16251385
                    ForeColor =1769599
                    Name ="Etichetta179"
                    Caption ="Cst Obj"
                    FontName ="Trebuchet"
                    LayoutCachedWidth =735
                    LayoutCachedHeight =225
                End
            End
        End
        Begin Section
            Height =3401
            BackColor =12311007
            Name ="Corpo"
            Begin
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =93
                    TextFontCharSet =161
                    TextAlign =2
                    Left =345
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtA1Np"
                    Caption ="11"
                    FontName ="Calibri"
                    LayoutCachedLeft =345
                    LayoutCachedWidth =1366
                    LayoutCachedHeight =286
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =1366
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtA2Np"
                    Caption ="0"
                    FontName ="Calibri"
                    LayoutCachedLeft =1366
                    LayoutCachedWidth =2387
                    LayoutCachedHeight =286
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =2387
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtA3Np"
                    Caption ="0"
                    FontName ="Calibri"
                    LayoutCachedLeft =2387
                    LayoutCachedWidth =3408
                    LayoutCachedHeight =286
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =3408
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtA4Np"
                    Caption ="0"
                    FontName ="Calibri"
                    LayoutCachedLeft =3408
                    LayoutCachedWidth =4429
                    LayoutCachedHeight =286
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =4429
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtB1NP"
                    Caption ="0"
                    FontName ="Calibri"
                    LayoutCachedLeft =4429
                    LayoutCachedWidth =5450
                    LayoutCachedHeight =286
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =5450
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtB2Np"
                    Caption ="0"
                    FontName ="Calibri"
                    LayoutCachedLeft =5450
                    LayoutCachedWidth =6471
                    LayoutCachedHeight =286
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =6471
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtB3Np"
                    Caption ="0"
                    FontName ="Calibri"
                    LayoutCachedLeft =6471
                    LayoutCachedWidth =7492
                    LayoutCachedHeight =286
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =7492
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtC1Np"
                    Caption ="0"
                    FontName ="Calibri"
                    LayoutCachedLeft =7492
                    LayoutCachedWidth =8513
                    LayoutCachedHeight =286
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =8513
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtC2Np"
                    Caption ="0"
                    FontName ="Calibri"
                    LayoutCachedLeft =8513
                    LayoutCachedWidth =9534
                    LayoutCachedHeight =286
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =1
                    Width =340
                    Height =300
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =255
                    Name ="Etichetta89"
                    Caption ="NP"
                    FontName ="Calibri"
                    LayoutCachedWidth =340
                    LayoutCachedHeight =300
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =3
                    Left =9534
                    Width =1021
                    Height =286
                    FontSize =11
                    FontWeight =700
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtNp"
                    Caption ="11"
                    FontName ="Calibri"
                    LayoutCachedLeft =9534
                    LayoutCachedWidth =10555
                    LayoutCachedHeight =286
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =345
                    Top =300
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtA1Vs"
                    Caption ="0"
                    FontName ="Calibri"
                    LayoutCachedLeft =345
                    LayoutCachedTop =300
                    LayoutCachedWidth =1366
                    LayoutCachedHeight =586
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =1366
                    Top =300
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtA2Vs"
                    Caption ="67.457"
                    FontName ="Calibri"
                    LayoutCachedLeft =1366
                    LayoutCachedTop =300
                    LayoutCachedWidth =2387
                    LayoutCachedHeight =586
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =2387
                    Top =300
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtA3Vs"
                    Caption ="0"
                    FontName ="Calibri"
                    LayoutCachedLeft =2387
                    LayoutCachedTop =300
                    LayoutCachedWidth =3408
                    LayoutCachedHeight =586
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =3408
                    Top =300
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtA4Vs"
                    Caption ="0"
                    FontName ="Calibri"
                    LayoutCachedLeft =3408
                    LayoutCachedTop =300
                    LayoutCachedWidth =4429
                    LayoutCachedHeight =586
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =4429
                    Top =300
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtB1Vs"
                    Caption ="0"
                    FontName ="Calibri"
                    LayoutCachedLeft =4429
                    LayoutCachedTop =300
                    LayoutCachedWidth =5450
                    LayoutCachedHeight =586
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =5450
                    Top =300
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtB2Vs"
                    Caption ="0"
                    FontName ="Calibri"
                    LayoutCachedLeft =5450
                    LayoutCachedTop =300
                    LayoutCachedWidth =6471
                    LayoutCachedHeight =586
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =6471
                    Top =300
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtB3Vs"
                    Caption ="0"
                    FontName ="Calibri"
                    LayoutCachedLeft =6471
                    LayoutCachedTop =300
                    LayoutCachedWidth =7492
                    LayoutCachedHeight =586
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =7492
                    Top =300
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtC1Vs"
                    Caption ="0"
                    FontName ="Calibri"
                    LayoutCachedLeft =7492
                    LayoutCachedTop =300
                    LayoutCachedWidth =8513
                    LayoutCachedHeight =586
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =8513
                    Top =300
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtC2Vs"
                    Caption ="0"
                    FontName ="Calibri"
                    LayoutCachedLeft =8513
                    LayoutCachedTop =300
                    LayoutCachedWidth =9534
                    LayoutCachedHeight =586
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =1
                    Left =-15
                    Top =300
                    Width =340
                    Height =300
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =255
                    Name ="Etichetta99"
                    Caption ="VS"
                    FontName ="Calibri"
                    LayoutCachedLeft =-15
                    LayoutCachedTop =300
                    LayoutCachedWidth =325
                    LayoutCachedHeight =600
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =87
                    TextFontCharSet =161
                    TextAlign =3
                    Left =9534
                    Top =300
                    Width =1021
                    Height =286
                    FontSize =11
                    FontWeight =700
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtVs"
                    Caption ="67.457"
                    FontName ="Calibri"
                    LayoutCachedLeft =9534
                    LayoutCachedTop =300
                    LayoutCachedWidth =10555
                    LayoutCachedHeight =586
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =345
                    Top =615
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtA1s"
                    Caption ="0"
                    FontName ="Calibri"
                    LayoutCachedLeft =345
                    LayoutCachedTop =615
                    LayoutCachedWidth =1366
                    LayoutCachedHeight =901
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =1366
                    Top =615
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtA2s"
                    Caption ="0"
                    FontName ="Calibri"
                    LayoutCachedLeft =1366
                    LayoutCachedTop =615
                    LayoutCachedWidth =2387
                    LayoutCachedHeight =901
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =2387
                    Top =615
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtA3s"
                    Caption ="0"
                    FontName ="Calibri"
                    LayoutCachedLeft =2387
                    LayoutCachedTop =615
                    LayoutCachedWidth =3408
                    LayoutCachedHeight =901
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =3408
                    Top =615
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtA4s"
                    Caption ="0"
                    FontName ="Calibri"
                    LayoutCachedLeft =3408
                    LayoutCachedTop =615
                    LayoutCachedWidth =4429
                    LayoutCachedHeight =901
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =4429
                    Top =615
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtB1s"
                    Caption ="0"
                    FontName ="Calibri"
                    LayoutCachedLeft =4429
                    LayoutCachedTop =615
                    LayoutCachedWidth =5450
                    LayoutCachedHeight =901
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =5450
                    Top =615
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtB2s"
                    Caption ="0"
                    FontName ="Calibri"
                    LayoutCachedLeft =5450
                    LayoutCachedTop =615
                    LayoutCachedWidth =6471
                    LayoutCachedHeight =901
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =6471
                    Top =615
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtB3s"
                    Caption ="52.092"
                    FontName ="Calibri"
                    LayoutCachedLeft =6471
                    LayoutCachedTop =615
                    LayoutCachedWidth =7492
                    LayoutCachedHeight =901
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =7492
                    Top =615
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtC1s"
                    Caption ="50.389"
                    FontName ="Calibri"
                    LayoutCachedLeft =7492
                    LayoutCachedTop =615
                    LayoutCachedWidth =8513
                    LayoutCachedHeight =901
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =8513
                    Top =615
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtC2s"
                    Caption ="0"
                    FontName ="Calibri"
                    LayoutCachedLeft =8513
                    LayoutCachedTop =615
                    LayoutCachedWidth =9534
                    LayoutCachedHeight =901
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =87
                    TextFontCharSet =161
                    TextAlign =1
                    Left =-15
                    Top =615
                    Width =340
                    Height =300
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =255
                    Name ="Etichetta110"
                    Caption ="S"
                    FontName ="Calibri"
                    LayoutCachedLeft =-15
                    LayoutCachedTop =615
                    LayoutCachedWidth =325
                    LayoutCachedHeight =915
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =87
                    TextFontCharSet =161
                    TextAlign =3
                    Left =9534
                    Top =615
                    Width =1021
                    Height =286
                    FontSize =11
                    FontWeight =700
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtS"
                    Caption ="102.481"
                    FontName ="Calibri"
                    LayoutCachedLeft =9534
                    LayoutCachedTop =615
                    LayoutCachedWidth =10555
                    LayoutCachedHeight =901
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =93
                    TextFontCharSet =161
                    TextAlign =2
                    Left =345
                    Top =945
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtA1Ms"
                    Caption ="0"
                    FontName ="Calibri"
                    LayoutCachedLeft =345
                    LayoutCachedTop =945
                    LayoutCachedWidth =1366
                    LayoutCachedHeight =1231
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =1366
                    Top =945
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtA2Ms"
                    Caption ="0"
                    FontName ="Calibri"
                    LayoutCachedLeft =1366
                    LayoutCachedTop =945
                    LayoutCachedWidth =2387
                    LayoutCachedHeight =1231
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =2387
                    Top =945
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtA3Ms"
                    Caption ="0"
                    FontName ="Calibri"
                    LayoutCachedLeft =2387
                    LayoutCachedTop =945
                    LayoutCachedWidth =3408
                    LayoutCachedHeight =1231
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =3408
                    Top =945
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtA4Ms"
                    Caption ="0"
                    FontName ="Calibri"
                    LayoutCachedLeft =3408
                    LayoutCachedTop =945
                    LayoutCachedWidth =4429
                    LayoutCachedHeight =1231
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =4429
                    Top =945
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtB1Ms"
                    Caption ="0"
                    FontName ="Calibri"
                    LayoutCachedLeft =4429
                    LayoutCachedTop =945
                    LayoutCachedWidth =5450
                    LayoutCachedHeight =1231
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =5450
                    Top =945
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtB2Ms"
                    Caption ="21.410"
                    FontName ="Calibri"
                    LayoutCachedLeft =5450
                    LayoutCachedTop =945
                    LayoutCachedWidth =6471
                    LayoutCachedHeight =1231
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =6471
                    Top =945
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtb3Ms"
                    Caption ="25.725"
                    FontName ="Calibri"
                    LayoutCachedLeft =6471
                    LayoutCachedTop =945
                    LayoutCachedWidth =7492
                    LayoutCachedHeight =1231
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =7492
                    Top =945
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtC1Ms"
                    Caption ="22.256"
                    FontName ="Calibri"
                    LayoutCachedLeft =7492
                    LayoutCachedTop =945
                    LayoutCachedWidth =8513
                    LayoutCachedHeight =1231
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =8513
                    Top =945
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtC2Ms"
                    Caption ="0"
                    FontName ="Calibri"
                    LayoutCachedLeft =8513
                    LayoutCachedTop =945
                    LayoutCachedWidth =9534
                    LayoutCachedHeight =1231
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =87
                    TextFontCharSet =161
                    TextAlign =1
                    Left =-15
                    Top =945
                    Width =340
                    Height =300
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =255
                    Name ="Etichetta121"
                    Caption ="MS"
                    FontName ="Calibri"
                    LayoutCachedLeft =-15
                    LayoutCachedTop =945
                    LayoutCachedWidth =325
                    LayoutCachedHeight =1245
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =87
                    TextFontCharSet =161
                    TextAlign =3
                    Left =9534
                    Top =945
                    Width =1021
                    Height =286
                    FontSize =11
                    FontWeight =700
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtMs"
                    Caption ="69.391"
                    FontName ="Calibri"
                    LayoutCachedLeft =9534
                    LayoutCachedTop =945
                    LayoutCachedWidth =10555
                    LayoutCachedHeight =1231
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =93
                    TextFontCharSet =161
                    TextAlign =2
                    Left =345
                    Top =1275
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtA1M"
                    Caption ="0"
                    FontName ="Calibri"
                    LayoutCachedLeft =345
                    LayoutCachedTop =1275
                    LayoutCachedWidth =1366
                    LayoutCachedHeight =1561
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =1366
                    Top =1275
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtA2M"
                    Caption ="0"
                    FontName ="Calibri"
                    LayoutCachedLeft =1366
                    LayoutCachedTop =1275
                    LayoutCachedWidth =2387
                    LayoutCachedHeight =1561
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =2387
                    Top =1275
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtA3M"
                    Caption ="0"
                    FontName ="Calibri"
                    LayoutCachedLeft =2387
                    LayoutCachedTop =1275
                    LayoutCachedWidth =3408
                    LayoutCachedHeight =1561
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =3408
                    Top =1275
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtA4M"
                    Caption ="31.832"
                    FontName ="Calibri"
                    LayoutCachedLeft =3408
                    LayoutCachedTop =1275
                    LayoutCachedWidth =4429
                    LayoutCachedHeight =1561
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =4429
                    Top =1275
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtB1M"
                    Caption ="18.138"
                    FontName ="Calibri"
                    LayoutCachedLeft =4429
                    LayoutCachedTop =1275
                    LayoutCachedWidth =5450
                    LayoutCachedHeight =1561
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =5450
                    Top =1275
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtB2M"
                    Caption ="17.244"
                    FontName ="Calibri"
                    LayoutCachedLeft =5450
                    LayoutCachedTop =1275
                    LayoutCachedWidth =6471
                    LayoutCachedHeight =1561
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =6471
                    Top =1275
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtB3M"
                    Caption ="17.981"
                    FontName ="Calibri"
                    LayoutCachedLeft =6471
                    LayoutCachedTop =1275
                    LayoutCachedWidth =7492
                    LayoutCachedHeight =1561
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =7492
                    Top =1275
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtC1M"
                    Caption ="12.253"
                    FontName ="Calibri"
                    LayoutCachedLeft =7492
                    LayoutCachedTop =1275
                    LayoutCachedWidth =8513
                    LayoutCachedHeight =1561
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =8513
                    Top =1275
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtC2M"
                    Caption ="0"
                    FontName ="Calibri"
                    LayoutCachedLeft =8513
                    LayoutCachedTop =1275
                    LayoutCachedWidth =9534
                    LayoutCachedHeight =1561
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =1
                    Left =-15
                    Top =1275
                    Width =340
                    Height =300
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =255
                    Name ="Etichetta132"
                    Caption ="M"
                    FontName ="Calibri"
                    LayoutCachedLeft =-15
                    LayoutCachedTop =1275
                    LayoutCachedWidth =325
                    LayoutCachedHeight =1575
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =3
                    Left =9534
                    Top =1275
                    Width =1021
                    Height =286
                    FontSize =11
                    FontWeight =700
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtM"
                    Caption ="97.448"
                    FontName ="Calibri"
                    LayoutCachedLeft =9534
                    LayoutCachedTop =1275
                    LayoutCachedWidth =10555
                    LayoutCachedHeight =1561
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =345
                    Top =1575
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtA1MF"
                    Caption ="0"
                    FontName ="Calibri"
                    LayoutCachedLeft =345
                    LayoutCachedTop =1575
                    LayoutCachedWidth =1366
                    LayoutCachedHeight =1861
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =1366
                    Top =1575
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtA2MF"
                    Caption ="0"
                    FontName ="Calibri"
                    LayoutCachedLeft =1366
                    LayoutCachedTop =1575
                    LayoutCachedWidth =2387
                    LayoutCachedHeight =1861
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =2387
                    Top =1575
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtA3MF"
                    Caption ="12.769"
                    FontName ="Calibri"
                    LayoutCachedLeft =2387
                    LayoutCachedTop =1575
                    LayoutCachedWidth =3408
                    LayoutCachedHeight =1861
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =3408
                    Top =1575
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtA4MF"
                    Caption ="9.251"
                    FontName ="Calibri"
                    LayoutCachedLeft =3408
                    LayoutCachedTop =1575
                    LayoutCachedWidth =4429
                    LayoutCachedHeight =1861
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =4429
                    Top =1575
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtB1MF"
                    Caption ="4.390"
                    FontName ="Calibri"
                    LayoutCachedLeft =4429
                    LayoutCachedTop =1575
                    LayoutCachedWidth =5450
                    LayoutCachedHeight =1861
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =5450
                    Top =1575
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtB2MF"
                    Caption ="5.466"
                    FontName ="Calibri"
                    LayoutCachedLeft =5450
                    LayoutCachedTop =1575
                    LayoutCachedWidth =6471
                    LayoutCachedHeight =1861
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =6471
                    Top =1575
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtB3MF"
                    Caption ="4.058"
                    FontName ="Calibri"
                    LayoutCachedLeft =6471
                    LayoutCachedTop =1575
                    LayoutCachedWidth =7492
                    LayoutCachedHeight =1861
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =7492
                    Top =1575
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtC1MF"
                    Caption ="2.558"
                    FontName ="Calibri"
                    LayoutCachedLeft =7492
                    LayoutCachedTop =1575
                    LayoutCachedWidth =8513
                    LayoutCachedHeight =1861
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =8513
                    Top =1575
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtC2MF"
                    Caption ="0"
                    FontName ="Calibri"
                    LayoutCachedLeft =8513
                    LayoutCachedTop =1575
                    LayoutCachedWidth =9534
                    LayoutCachedHeight =1861
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =1
                    Left =-15
                    Top =1575
                    Width =340
                    Height =300
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =255
                    Name ="Etichetta143"
                    Caption ="MF"
                    FontName ="Calibri"
                    LayoutCachedLeft =-15
                    LayoutCachedTop =1575
                    LayoutCachedWidth =325
                    LayoutCachedHeight =1875
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =87
                    TextFontCharSet =161
                    TextAlign =3
                    Left =9534
                    Top =1575
                    Width =1021
                    Height =286
                    FontSize =11
                    FontWeight =700
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtMF"
                    Caption ="38.492"
                    FontName ="Calibri"
                    LayoutCachedLeft =9534
                    LayoutCachedTop =1575
                    LayoutCachedWidth =10555
                    LayoutCachedHeight =1861
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =345
                    Top =1890
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtA1F"
                    Caption ="0"
                    FontName ="Calibri"
                    LayoutCachedLeft =345
                    LayoutCachedTop =1890
                    LayoutCachedWidth =1366
                    LayoutCachedHeight =2176
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =1366
                    Top =1890
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtA2F"
                    Caption ="22.092"
                    FontName ="Calibri"
                    LayoutCachedLeft =1366
                    LayoutCachedTop =1890
                    LayoutCachedWidth =2387
                    LayoutCachedHeight =2176
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =2387
                    Top =1890
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtA3F"
                    Caption ="28.467"
                    FontName ="Calibri"
                    LayoutCachedLeft =2387
                    LayoutCachedTop =1890
                    LayoutCachedWidth =3408
                    LayoutCachedHeight =2176
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =3408
                    Top =1890
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtA4F"
                    Caption ="18.365"
                    FontName ="Calibri"
                    LayoutCachedLeft =3408
                    LayoutCachedTop =1890
                    LayoutCachedWidth =4429
                    LayoutCachedHeight =2176
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =4429
                    Top =1890
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtB1F"
                    Caption ="8.568"
                    FontName ="Calibri"
                    LayoutCachedLeft =4429
                    LayoutCachedTop =1890
                    LayoutCachedWidth =5450
                    LayoutCachedHeight =2176
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =5450
                    Top =1890
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtB2F"
                    Caption ="7.585"
                    FontName ="Calibri"
                    LayoutCachedLeft =5450
                    LayoutCachedTop =1890
                    LayoutCachedWidth =6471
                    LayoutCachedHeight =2176
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =6471
                    Top =1890
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtB3F"
                    Caption ="5.135"
                    FontName ="Calibri"
                    LayoutCachedLeft =6471
                    LayoutCachedTop =1890
                    LayoutCachedWidth =7492
                    LayoutCachedHeight =2176
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =7492
                    Top =1890
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtC1F"
                    Caption ="2.463"
                    FontName ="Calibri"
                    LayoutCachedLeft =7492
                    LayoutCachedTop =1890
                    LayoutCachedWidth =8513
                    LayoutCachedHeight =2176
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =8513
                    Top =1890
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtC2F"
                    Caption ="0"
                    FontName ="Calibri"
                    LayoutCachedLeft =8513
                    LayoutCachedTop =1890
                    LayoutCachedWidth =9534
                    LayoutCachedHeight =2176
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =87
                    TextFontCharSet =161
                    TextAlign =1
                    Left =-15
                    Top =1890
                    Width =340
                    Height =300
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =255
                    Name ="Etichetta154"
                    Caption ="F"
                    FontName ="Calibri"
                    LayoutCachedLeft =-15
                    LayoutCachedTop =1890
                    LayoutCachedWidth =325
                    LayoutCachedHeight =2190
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =87
                    TextFontCharSet =161
                    TextAlign =3
                    Left =9534
                    Top =1890
                    Width =1021
                    Height =286
                    FontSize =11
                    FontWeight =700
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtF"
                    Caption ="92.675"
                    FontName ="Calibri"
                    LayoutCachedLeft =9534
                    LayoutCachedTop =1890
                    LayoutCachedWidth =10555
                    LayoutCachedHeight =2176
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =93
                    TextFontCharSet =161
                    TextAlign =2
                    Left =345
                    Top =2220
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtA1VF"
                    Caption ="265.825"
                    FontName ="Calibri"
                    LayoutCachedLeft =345
                    LayoutCachedTop =2220
                    LayoutCachedWidth =1366
                    LayoutCachedHeight =2506
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =1366
                    Top =2220
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtA2VF"
                    Caption ="36.061"
                    FontName ="Calibri"
                    LayoutCachedLeft =1366
                    LayoutCachedTop =2220
                    LayoutCachedWidth =2387
                    LayoutCachedHeight =2506
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =2387
                    Top =2220
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtA3VF"
                    Caption ="30.802"
                    FontName ="Calibri"
                    LayoutCachedLeft =2387
                    LayoutCachedTop =2220
                    LayoutCachedWidth =3408
                    LayoutCachedHeight =2506
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =3408
                    Top =2220
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtA4VF"
                    Caption ="19.612"
                    FontName ="Calibri"
                    LayoutCachedLeft =3408
                    LayoutCachedTop =2220
                    LayoutCachedWidth =4429
                    LayoutCachedHeight =2506
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =4429
                    Top =2220
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtB1VF"
                    Caption ="7.506"
                    FontName ="Calibri"
                    LayoutCachedLeft =4429
                    LayoutCachedTop =2220
                    LayoutCachedWidth =5450
                    LayoutCachedHeight =2506
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =5450
                    Top =2220
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtB2VF"
                    Caption ="4.604"
                    FontName ="Calibri"
                    LayoutCachedLeft =5450
                    LayoutCachedTop =2220
                    LayoutCachedWidth =6471
                    LayoutCachedHeight =2506
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =6471
                    Top =2220
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtB3VF"
                    Caption ="2.684"
                    FontName ="Calibri"
                    LayoutCachedLeft =6471
                    LayoutCachedTop =2220
                    LayoutCachedWidth =7492
                    LayoutCachedHeight =2506
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =7492
                    Top =2220
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtC1VF"
                    Caption ="1.133"
                    FontName ="Calibri"
                    LayoutCachedLeft =7492
                    LayoutCachedTop =2220
                    LayoutCachedWidth =8513
                    LayoutCachedHeight =2506
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =8513
                    Top =2220
                    Width =1021
                    Height =286
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtC2VF"
                    Caption ="0"
                    FontName ="Calibri"
                    LayoutCachedLeft =8513
                    LayoutCachedTop =2220
                    LayoutCachedWidth =9534
                    LayoutCachedHeight =2506
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =1
                    Left =-15
                    Top =2220
                    Width =340
                    Height =300
                    FontSize =11
                    BackColor =-2147483643
                    ForeColor =255
                    Name ="Etichetta165"
                    Caption ="VF"
                    FontName ="Calibri"
                    LayoutCachedLeft =-15
                    LayoutCachedTop =2220
                    LayoutCachedWidth =325
                    LayoutCachedHeight =2520
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =3
                    Left =9534
                    Top =2220
                    Width =1021
                    Height =286
                    FontSize =11
                    FontWeight =700
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtVF"
                    Caption ="368.228"
                    FontName ="Calibri"
                    LayoutCachedLeft =9534
                    LayoutCachedTop =2220
                    LayoutCachedWidth =10555
                    LayoutCachedHeight =2506
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =345
                    Top =2520
                    Width =1021
                    Height =286
                    FontSize =11
                    FontWeight =700
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtA1"
                    Caption ="265.836"
                    FontName ="Calibri"
                    LayoutCachedLeft =345
                    LayoutCachedTop =2520
                    LayoutCachedWidth =1366
                    LayoutCachedHeight =2806
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =1366
                    Top =2520
                    Width =1021
                    Height =286
                    FontSize =11
                    FontWeight =700
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtA2"
                    Caption ="125.611"
                    FontName ="Calibri"
                    LayoutCachedLeft =1366
                    LayoutCachedTop =2520
                    LayoutCachedWidth =2387
                    LayoutCachedHeight =2806
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =2387
                    Top =2520
                    Width =1021
                    Height =286
                    FontSize =11
                    FontWeight =700
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtA3"
                    Caption ="72.038"
                    FontName ="Calibri"
                    LayoutCachedLeft =2387
                    LayoutCachedTop =2520
                    LayoutCachedWidth =3408
                    LayoutCachedHeight =2806
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =3408
                    Top =2520
                    Width =1021
                    Height =286
                    FontSize =11
                    FontWeight =700
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtA4"
                    Caption ="79.060"
                    FontName ="Calibri"
                    LayoutCachedLeft =3408
                    LayoutCachedTop =2520
                    LayoutCachedWidth =4429
                    LayoutCachedHeight =2806
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =4429
                    Top =2520
                    Width =1021
                    Height =286
                    FontSize =11
                    FontWeight =700
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtB1"
                    Caption ="38.602"
                    FontName ="Calibri"
                    LayoutCachedLeft =4429
                    LayoutCachedTop =2520
                    LayoutCachedWidth =5450
                    LayoutCachedHeight =2806
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =5450
                    Top =2520
                    Width =1021
                    Height =286
                    FontSize =11
                    FontWeight =700
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtB2"
                    Caption ="56.309"
                    FontName ="Calibri"
                    LayoutCachedLeft =5450
                    LayoutCachedTop =2520
                    LayoutCachedWidth =6471
                    LayoutCachedHeight =2806
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =6471
                    Top =2520
                    Width =1021
                    Height =286
                    FontSize =11
                    FontWeight =700
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtB3"
                    Caption ="55.584"
                    FontName ="Calibri"
                    LayoutCachedLeft =6471
                    LayoutCachedTop =2520
                    LayoutCachedWidth =7492
                    LayoutCachedHeight =2806
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =7492
                    Top =2520
                    Width =1021
                    Height =286
                    FontSize =11
                    FontWeight =700
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtC1"
                    Caption ="91.051"
                    FontName ="Calibri"
                    LayoutCachedLeft =7492
                    LayoutCachedTop =2520
                    LayoutCachedWidth =8513
                    LayoutCachedHeight =2806
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =95
                    TextFontCharSet =161
                    TextAlign =2
                    Left =8513
                    Top =2520
                    Width =1021
                    Height =286
                    FontSize =11
                    FontWeight =700
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtC2"
                    Caption ="0"
                    FontName ="Calibri"
                    LayoutCachedLeft =8513
                    LayoutCachedTop =2520
                    LayoutCachedWidth =9534
                    LayoutCachedHeight =2806
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =87
                    TextFontCharSet =161
                    TextAlign =1
                    Left =-15
                    Top =2520
                    Width =340
                    Height =300
                    FontSize =11
                    FontWeight =700
                    BackColor =-2147483643
                    ForeColor =255
                    Name ="Etichetta177"
                    Caption ="T."
                    FontName ="Calibri"
                    LayoutCachedLeft =-15
                    LayoutCachedTop =2520
                    LayoutCachedWidth =325
                    LayoutCachedHeight =2820
                End
                Begin Label
                    SpecialEffect =2
                    BackStyle =1
                    OldBorderStyle =1
                    OverlapFlags =87
                    TextFontCharSet =161
                    TextAlign =3
                    Left =9534
                    Top =2520
                    Width =1021
                    Height =286
                    FontSize =11
                    FontWeight =700
                    BackColor =-2147483643
                    ForeColor =-2147483640
                    Name ="txtTot"
                    Caption ="784.091"
                    FontName ="Calibri"
                    LayoutCachedLeft =9534
                    LayoutCachedTop =2520
                    LayoutCachedWidth =10555
                    LayoutCachedHeight =2806
                End
                Begin Line
                    LineSlant = NotDefault
                    OverlapFlags =85
                    Top =2955
                    Width =10601
                    Name ="Linea180"
                    LayoutCachedTop =2955
                    LayoutCachedWidth =10601
                    LayoutCachedHeight =2955
                End
            End
        End
        Begin FormFooter
            Visible = NotDefault
            Height =0
            BackColor =-2147483633
            Name ="PièDiPaginaMaschera"
        End
    End
End
CodeBehindForm
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = False
Option Compare Database
Option Explicit
